apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: container-security-operator
spec:
  sourceType: grpc
  image: quay.io/quay/cso-catalog@sha256:d25cdd90fdef0bc9e03b97b7b3a1c894467b906274575608950a9c1b002fe44b
