apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: imagemanifestvulns.secscan.quay.redhat.com
spec:
  group: secscan.quay.redhat.com
  names:
    kind: ImageManifestVuln
    listKind: ImageManifestVulnList
    plural: imagemanifestvulns
    singular: imagemanifestvuln
  scope: Namespaced
  version: v1alpha1
